In [3]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import csv

In [2]:
df = pd.DataFrame(np.arange(9).reshape(3,3), index=list('abc'), columns=list('xyz'))
series = df['y']
print(df)
print(series)

def f2(x: pd.Series)-> pd.Series:
    return pd.Series([x.min(), x.max()], index=['min','max'])

x = df.apply(f2, axis='columns')
x

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8
a    1
b    4
c    7
Name: y, dtype: int64


min  max
a    0    2
b    3    5
c    6    8

In [ ]:
def my_format(x:float) -> str:
    return f"{x:.2f}"

def my_format2(x:float) -> str:
    return f"{x:.4f}"

x = df['y'].map(my_format)#SERIES
y = df.map(my_format2)#DATA FRAME

print(x)
print(y)

a    2.00
b    2.00
c    2.00
Name: y, dtype: object
        x       y        z
a  3.0000  2.0000   7.0000
b  6.0000  2.0000  10.0000
c  9.0000  2.0000  13.0000


In [55]:
def my_func(s: pd.Series) -> pd.Series:
    return s+s.iloc[1]  
x = df.apply(my_func, axis=0)  
x['y'] = np.nan
df = x.fillna(2).astype(int)
print(df)



    x  y   z
a   9  2  17
b  12  2  20
c  15  2  23


In [62]:
obj = pd.Series(range(4), index = list('cadb'))
x= obj.sort_index()
print(x)

a    1
b    3
c    0
d    2
dtype: int64


In [80]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)), index=list('cba'), columns=['three','one','two'])
# df = df.sort_index(axis='index')
# df = df.sort_index(axis='index', ascending=False)
print(df)
def sortx(x:pd.Series) ->pd.Series:
    return x.sort_values()

objx = df.apply(sorted,axis='index')
print(objx)

# obj = pd.Series([3,-1,-3,0])
# obj = obj.sort_values()
# print(obj)


   three  one  two
c      9    0    6
b      0    6    1
a      1    7    8
   three  one  two
c      0    0    1
b      1    6    6
a      9    7    8


In [ ]:
obj = pd.Series([7,-5,4,4,2,0,7])
obj = obj.rank()
obj = obj.rank(method='first')
obj = obj.rank(ascending=False)

0    6.5
1    1.0
2    4.5
3    4.5
4    3.0
5    2.0
6    6.5
dtype: float64

In [8]:
#ZADANIE 1.
rng = np.random.default_rng(seed=0)
dfq = pd.DataFrame(rng.integers(10,51,(5,4)), index=list('abcde'), columns=['A','B','C','D'])
print(dfq)
#ZADANIE 2.
col_b = dfq['B']
row_b = dfq.loc[['b','d']]

element = dfq.iloc[1,2]

dfq['C'] = dfq['C']**2 


#ZADANIE 3.


mask = dfq[dfq['A']>30]


dfq[dfq<20] = np.nan
dfq = dfq.fillna(-1).astype(int)
print(dfq)

#ZADANIE 4.

def random_coince(x):
    lista = ['X','Y']
    return np.random.choice(lista)

dfq['kategoria'] = dfq.apply(random_coince, axis='columns') 
# df["Kategoria"] = np.random.choice(["X", "Y"], size=len(df))
# avg_D = df.groupby("Kategoria")["D"].mean()

print(dfq)



    A   B   C   D
a  44  36  30  21
b  22  11  13  10
c  17  43  36  47
d  30  34  49  39
e  35  32  32  48
    A   B     C   D
a  44  36   900  21
b  22  -1   169  -1
c  -1  43  1296  47
d  30  34  2401  39
e  35  32  1024  48
    A   B     C   D kategoria
a  44  36   900  21         X
b  22  -1   169  -1         Y
c  -1  43  1296  47         X
d  30  34  2401  39         Y
e  35  32  1024  48         Y


In [ ]:
matrix = np.arange(25).reshape(5,5)
matrix_to_vecotr = matrix.reshape(1,25)
matrix = matrix*2
above_15 = matrix[matrix>15]
matrix_mean = np.mean(matrix)
sum_of_matrxi = np.sum(matrix[:,0])



[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
100


In [43]:
price = pd.read_pickle("przykłady/yahoo_ceny.pkl")

volume = pd.read_pickle("przykłady/yahoo_liczby.pkl")

returns = price.pct_change()
returns.tail()

returns['GOOG'].corr(returns['IBM'])
returns['GOOG'].cov(returns['IBM']).round(4)

# returns.corr()

# returns.cov()




np.float64(0.0001)

In [96]:
obj = pd.Series(['a','b','c','a','a','a','c','c','b'])

unique_values = obj.unique()
obj_counts = obj.value_counts()

indices = pd.Index(unique_values).get_indexer(obj)
obj_counts



a    4
c    3
b    2
Name: count, dtype: int64

In [ ]:
data = pd.DataFrame({"A":[1,5,1,5],
                     "B":[3,2,3,4],
                     "C":[1,5,1,5]})


data["B"].value_counts()

# data[data >2] = np.nan
# data = data.fillna(0)

data.value_counts()

# df = pd.DataFrame(data)
# df = df.fillna("X")

reslut = data.stack().value_counts()
reslut



1    4
5    4
3    2
2    1
4    1
Name: count, dtype: int64

In [2]:
df = pd.DataFrame({"ID":(range(1,7)),
                "Name":["Anna", "Bob", "Cecilia","David","Eva","Frank"],
                "Age":[25,30,22,35,28,40],
                "Score":[88.5, np.nan, 92.0, 75.0, np.nan, 85.0],
                "City":["NY", "LA", "NY", "CHI", "LA", "NY"]},columns=["ID","Name","Age","Score","City"])

age_abowe = df[df["Age"]>28]
x = age_abowe["Name"]
y = age_abowe["Score"]
#df[df["Age"]>28][["Name","Score"]]


df["Score"] = df["Score"].fillna(np.mean(df["Score"]))
#df["Score"].fillna(df["Score"].mean(), inplace=True)

avg_scores = df.groupby("City")[["Age", "Score"]].mean()
df["Passed"] = df["Score"]>=80
df

ID     Name  Age   Score City  Passed
0   1     Anna   25  88.500   NY    True
1   2      Bob   30  85.125   LA    True
2   3  Cecilia   22  92.000   NY    True
3   4    David   35  75.000  CHI   False
4   5      Eva   28  85.125   LA    True
5   6    Frank   40  85.000   NY    True

In [15]:
#!cat przykłady/ex1.csv
names = ['a','b','c','d','message']
df = pd.read_csv('przykłady/ex2.csv', names=names, index_col='message')
df


a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12