In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import csv
import sys

In [2]:
df = pd.DataFrame(np.arange(9).reshape(3,3), index=list('abc'), columns=list('xyz'))
series = df['y']
print(df)
print(series)

def f2(x: pd.Series)-> pd.Series:
    return pd.Series([x.min(), x.max()], index=['min','max'])

x = df.apply(f2, axis='columns')
x

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8
a    1
b    4
c    7
Name: y, dtype: int64


min  max
a    0    2
b    3    5
c    6    8

In [ ]:
def my_format(x:float) -> str:
    return f"{x:.2f}"

def my_format2(x:float) -> str:
    return f"{x:.4f}"

x = df['y'].map(my_format)#SERIES
y = df.map(my_format2)#DATA FRAME

print(x)
print(y)

a    2.00
b    2.00
c    2.00
Name: y, dtype: object
        x       y        z
a  3.0000  2.0000   7.0000
b  6.0000  2.0000  10.0000
c  9.0000  2.0000  13.0000


In [55]:
def my_func(s: pd.Series) -> pd.Series:
    return s+s.iloc[1]  
x = df.apply(my_func, axis=0)  
x['y'] = np.nan
df = x.fillna(2).astype(int)
print(df)



    x  y   z
a   9  2  17
b  12  2  20
c  15  2  23


In [62]:
obj = pd.Series(range(4), index = list('cadb'))
x= obj.sort_index()
print(x)

a    1
b    3
c    0
d    2
dtype: int64


In [80]:
df = pd.DataFrame(np.random.randint(0,10,(3,3)), index=list('cba'), columns=['three','one','two'])
# df = df.sort_index(axis='index')
# df = df.sort_index(axis='index', ascending=False)
print(df)
def sortx(x:pd.Series) ->pd.Series:
    return x.sort_values()

objx = df.apply(sorted,axis='index')
print(objx)

# obj = pd.Series([3,-1,-3,0])
# obj = obj.sort_values()
# print(obj)


   three  one  two
c      9    0    6
b      0    6    1
a      1    7    8
   three  one  two
c      0    0    1
b      1    6    6
a      9    7    8


In [ ]:
obj = pd.Series([7,-5,4,4,2,0,7])
obj = obj.rank()
obj = obj.rank(method='first')
obj = obj.rank(ascending=False)

0    6.5
1    1.0
2    4.5
3    4.5
4    3.0
5    2.0
6    6.5
dtype: float64

In [8]:
#ZADANIE 1.
rng = np.random.default_rng(seed=0)
dfq = pd.DataFrame(rng.integers(10,51,(5,4)), index=list('abcde'), columns=['A','B','C','D'])
print(dfq)
#ZADANIE 2.
col_b = dfq['B']
row_b = dfq.loc[['b','d']]

element = dfq.iloc[1,2]

dfq['C'] = dfq['C']**2 


#ZADANIE 3.


mask = dfq[dfq['A']>30]


dfq[dfq<20] = np.nan
dfq = dfq.fillna(-1).astype(int)
print(dfq)

#ZADANIE 4.

def random_coince(x):
    lista = ['X','Y']
    return np.random.choice(lista)

dfq['kategoria'] = dfq.apply(random_coince, axis='columns') 
# df["Kategoria"] = np.random.choice(["X", "Y"], size=len(df))
# avg_D = df.groupby("Kategoria")["D"].mean()

print(dfq)



    A   B   C   D
a  44  36  30  21
b  22  11  13  10
c  17  43  36  47
d  30  34  49  39
e  35  32  32  48
    A   B     C   D
a  44  36   900  21
b  22  -1   169  -1
c  -1  43  1296  47
d  30  34  2401  39
e  35  32  1024  48
    A   B     C   D kategoria
a  44  36   900  21         X
b  22  -1   169  -1         Y
c  -1  43  1296  47         X
d  30  34  2401  39         Y
e  35  32  1024  48         Y


In [ ]:
matrix = np.arange(25).reshape(5,5)
matrix_to_vecotr = matrix.reshape(1,25)
matrix = matrix*2
above_15 = matrix[matrix>15]
matrix_mean = np.mean(matrix)
sum_of_matrxi = np.sum(matrix[:,0])



[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
100


In [43]:
price = pd.read_pickle("przykłady/yahoo_ceny.pkl")

volume = pd.read_pickle("przykłady/yahoo_liczby.pkl")

returns = price.pct_change()
returns.tail()

returns['GOOG'].corr(returns['IBM'])
returns['GOOG'].cov(returns['IBM']).round(4)

# returns.corr()

# returns.cov()




np.float64(0.0001)

In [96]:
obj = pd.Series(['a','b','c','a','a','a','c','c','b'])

unique_values = obj.unique()
obj_counts = obj.value_counts()

indices = pd.Index(unique_values).get_indexer(obj)
obj_counts



a    4
c    3
b    2
Name: count, dtype: int64

In [ ]:
data = pd.DataFrame({"A":[1,5,1,5],
                     "B":[3,2,3,4],
                     "C":[1,5,1,5]})


data["B"].value_counts()

# data[data >2] = np.nan
# data = data.fillna(0)

data.value_counts()

# df = pd.DataFrame(data)
# df = df.fillna("X")

result = data.stack().value_counts()
result



1    4
5    4
3    2
2    1
4    1
Name: count, dtype: int64

In [2]:
df = pd.DataFrame({"ID":(range(1,7)),
                "Name":["Anna", "Bob", "Cecilia","David","Eva","Frank"],
                "Age":[25,30,22,35,28,40],
                "Score":[88.5, np.nan, 92.0, 75.0, np.nan, 85.0],
                "City":["NY", "LA", "NY", "CHI", "LA", "NY"]},columns=["ID","Name","Age","Score","City"])

age_abowe = df[df["Age"]>28]
x = age_abowe["Name"]
y = age_abowe["Score"]
#df[df["Age"]>28][["Name","Score"]]


df["Score"] = df["Score"].fillna(np.mean(df["Score"]))
#df["Score"].fillna(df["Score"].mean(), inplace=True)

avg_scores = df.groupby("City")[["Age", "Score"]].mean()
df["Passed"] = df["Score"]>=80
df

ID     Name  Age   Score City  Passed
0   1     Anna   25  88.500   NY    True
1   2      Bob   30  85.125   LA    True
2   3  Cecilia   22  92.000   NY    True
3   4    David   35  75.000  CHI   False
4   5      Eva   28  85.125   LA    True
5   6    Frank   40  85.000   NY    True

In [15]:
#!cat przykłady/ex1.csv
names = ['a','b','c','d','message']
df = pd.read_csv('przykłady/ex2.csv', names=names, index_col='message')
df


a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [20]:
#!cat przykłady/csv_mindex.csv
parsed = pd.read_csv('przykłady/csv_mindex.csv', index_col=['key1','key2'])
parsed

result = pd.read_csv("przykłady/ex5.csv", na_values=[4])
result



something  a   b     c     d message
0       one  1   2   3.0   NaN     NaN
1       two  5   6   NaN   8.0   world
2     three  9  10  11.0  12.0     foo

In [57]:
pd.options.display.max_rows = 20
result = pd.read_csv("przykłady/ex6.csv", nrows=3)
# result.to_csv("jakis_plik.csv")
result.to_csv(sys.stdout, sep= '|')



chunker = pd.read_csv("przykłady/ex6.csv", chunksize=1000)
tot = pd.Series([],dtype='int64')
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)

tot[:10]


|one|two|three|four|key
0|0.467976300189|-0.0386485396255|-0.295344251987|-1.82472622729|L
1|-0.358893469543|1.40445260007|0.704964644926|-0.200638304015|B
2|-0.50184039929|0.659253707223|-0.421690619312|-0.0576883018364|G


key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [39]:
df = pd.DataFrame(np.arange(9).reshape(3,3),columns=['a','b','c'])
df.loc[len(df)] = [0,1,2]
df.loc[len(df)] = [0,1,2]
x = df["c"].value_counts()
print(x)
df

c
2    3
5    1
8    1
Name: count, dtype: int64


a  b  c
0  0  1  2
1  3  4  5
2  6  7  8
3  0  1  2
4  0  1  2

In [ ]:
!cat przykłady/ex7.csv

f = open("przykłady/ex7.csv")
reader = csv.reader(f)
for line in reader:
    print(line)
f.close()

"a","b","c"
"1","2","3"
"1","2","3"
['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']


In [2]:
with open('przykłady/ex7.csv') as f:
    lines = list(csv.reader(f))
header, values = lines[0],lines[1:]

data_dict = {h: v for h,v in zip(header, zip(*values))}
data_dict








{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [89]:
data = {
    "Imię": ["Anna", "Jan", "Kasia", "Marek", "Ola"],
    "Wiek": [21, 22, 20, 23, 21],
    "Ocena": [4.5, 3.8, 5.0, 2.5, 4.2],
    "Miasto": ["Warszawa", "Kraków", "Gdańsk", "Wrocław", "Warszawa"]
}

df = pd.DataFrame(data)

df.iloc[:,[1]]
df['Ocena'].mean()
df[df["Miasto"] == 'Warszawa']
df["Stypendium"] = np.where(df["Ocena"]>=4.5, "Tak", "Nie")
df  =df.sort_values(by='Ocena',ascending=False)
df


Imię  Wiek  Ocena    Miasto Stypendium
2  Kasia    20    5.0    Gdańsk        Tak
0   Anna    21    4.5  Warszawa        Tak
4    Ola    21    4.2  Warszawa        Nie
1    Jan    22    3.8    Kraków        Nie
3  Marek    23    2.5   Wrocław        Nie

In [ ]:
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

f = open("przykłady/ex7.csv")
reader = csv.reader(f, dialect=my_dialect)
f.close()


In [97]:
data = {
    "Produkt": ["Laptop", "Telefon", "Telewizor", "Krzesło", "Stół"],
    "Kategoria": ["Elektronika", "Elektronika", "Elektronika", "Meble", "Meble"],
    "Cena": [4000, 2500, 3000, 350, 800],
    "Sprzedane_sztuki": [5, 8, 3, 10, 6]
}


df = pd.DataFrame(data)
df["Przychod"] = df["Cena"] * df["Sprzedane_sztuki"]
df["Status"] = np.where(df["Sprzedane_sztuki"]>5 ,"Dobrze",
                        np.where(df["Sprzedane_sztuki"]== 5, "srednio", "Zle"))


df["Przychod"].sum()
df[df["Kategoria"]=='Elektronika']
df =df.sort_values(by='Przychod',ascending=False)

In [14]:
with open('mydata2.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one','two','three'))
    writer.writerow(('1','2','3'))
    writer.writerow(('4','5','6'))
    writer.writerow(('7','8','9'))

In [110]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import csv
import sys
import json
from lxml import objectify
from io import StringIO
import matplotlib.pyplot as plt
import os
import requests
import sqlite3


In [24]:
path = "dane/mta_perf/Performance_MNR.xml"
# with open(path) as f:
#     parsed = objectify.parse(f)
# root = parsed.getroot()

# data = []

# skip_fields = ['PARENT_SEQ','INDICATOR_SEQ','DESIRED_CHANGE', 'DECIMAL_PLACES']

# for elt in root.INDICATOR:
#     el_data = {}
#     for child in elt.getchildren():
#         if child.tag in skip_fields:
#             continue
#         el_data[child.tag] = child.pyva
#     data.append(el_data)

perf = pd.read_xml(path)
perf



INDICATOR_SEQ  PARENT_SEQ           AGENCY_NAME  \
0            28445         NaN  Metro-North Railroad   
1            28445         NaN  Metro-North Railroad   
2            28445         NaN  Metro-North Railroad   
..             ...         ...                   ...   
645         373889         NaN  Metro-North Railroad   
646         373889         NaN  Metro-North Railroad   
647         373889         NaN  Metro-North Railroad   

                           INDICATOR_NAME  \
0    On-Time Performance (West of Hudson)   
1    On-Time Performance (West of Hudson)   
2    On-Time Performance (West of Hudson)   
..                                    ...   
645                Escalator Availability   
646                Escalator Availability   
647                Escalator Availability   

                                           DESCRIPTION  PERIOD_YEAR  \
0    Percent of commuter trains that arrive at thei...         2008   
1    Percent of commuter trains that arrive at thei...         2008   
2    Percent of commuter trains that arrive at thei...         2008   
..                                                 ...          ...   
645  Percent of the time that escalators are operat...         2011   
646  Percent of the time that escalators are operat...         2011   
647  Percent of the time that escalators are operat...         2011   

     PERIOD_MONTH            CATEGORY FREQUENCY DESIRED_CHANGE INDICATOR_UNIT  \
0               1  Service Indicators         M              U              %   
1               2  Service Indicators         M              U              %   
2               3  Service Indicators         M              U              %   
..            ...                 ...       ...            ...            ...   
645            10  Service Indicators         M              U              %   
646            11  Service Indicators         M              U              %   
647            12  Service Indicators         M              U              %   

     DECIMAL_PLACES YTD_TARGET YTD_ACTUAL MONTHLY_TARGET MONTHLY_ACTUAL  
0                 1      95.00      96.90          95.00          96.90  
1                 1      95.00      96.00          95.00          95.00  
2                 1      95.00      96.30          95.00          96.90  
..              ...        ...        ...            ...            ...  
645               1      97.00       None          97.00           None  
646               1      97.00       None          97.00           None  
647               1      97.00       None          97.00           None  

[648 rows x 16 columns]

In [ ]:
# obj = """
# {"name": "Wes",
# "cities_lived" : ["Akron", "Menchester", "Dubai"],
# "pet": null,
# "siblings": [
# {"name": "Scott", "age": 34,"hobbies" : ["soccer","video games"]},
# {"name": "Ana", "age": 23, "hobbies" : ["tenis","tiktok"]}
# ]
# }
# """

In [ ]:
# result = json.loads(obj)
# siblings = pd.DataFrame(result['siblings'],columns=["name", "age"])
# siblings_transposed = siblings.set_index('name').T
# # siblings = siblings.explode("hobbies").count()
# # siblings = siblings.groupby("name")["hobbies"].count()
# print(siblings_transposed)

name  Scott  Ana
age      34   23


In [101]:
data ='''ID	Imię	Nazwisko	Wiek	Ocena	Kierunek
1	Jan	Kowalski	21	3.8	Informatyka
2	Anna	Nowak	22	4.5	Matematyka
3	Adam	Kowalski	23	3.2	Informatyka
4	Ewa	Nowak	21	4.9	Biologia
5	Tomasz	Lewandowski	24	2.9	Informatyka
6	Ola	Wiśniewska	25	3.4	Chemia
7	Kamil	Zieliński	22	3.7	Matematyka'''

df = pd.read_csv(StringIO(data), sep ='\t', na_values=["Chemia"])
df.to_csv("nowy_plik.csv", index=False)

df = df.set_index("ID")
df.fillna("Angielski")

Imię     Nazwisko  Wiek  Ocena     Kierunek
ID                                               
1      Jan     Kowalski    21    3.8  Informatyka
2     Anna        Nowak    22    4.5   Matematyka
3     Adam     Kowalski    23    3.2  Informatyka
4      Ewa        Nowak    21    4.9     Biologia
5   Tomasz  Lewandowski    24    2.9  Informatyka
6      Ola   Wiśniewska    25    3.4    Angielski
7    Kamil    Zieliński    22    3.7   Matematyka

In [ ]:

# data = pd.read_json('przykłady/example.json')
# data.to_json(sys.stdout, orient="records")

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

In [109]:
tabels = pd.read_html('przykłady/fdic_failed_bank_list.html')
len(tabels)

failures = tabels[0]
pd.set_option('display.max_rows', 20)

close_timestamps = pd.to_datetime(failures["Closing Date"])

counts = close_timestamps.dt.year.value_counts().to_frame(name=("count"))

print(counts)



              count
Closing Date       
2010            157
2009            140
2011             92
2012             51
2008             25
2013             24
2014             18
2002             11
2015              8
2016              5
2004              4
2001              4
2007              3
2003              3
2000              2


In [26]:
frame = pd.read_csv("przykłady/ex1.csv")

frame.to_pickle('przykłady/frame_pickle')
pd.read_pickle("przykłady/frame_pickle")

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [40]:
xlsx = pd.ExcelFile('przykłady/ex1.xlsx')
xlsx.sheet_names
xlsx.parse(sheet_name='Sheet1',index_col=0)




a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [141]:
list_of_numbers = [4,3,5,2,3,4,1,3,2,8,4]
def bubble_sort():
    for j in range(len(list_of_numbers)):
        for i in range(len(list_of_numbers)-1):
            if list_of_numbers[i] > list_of_numbers[i+1]:
                temp = list_of_numbers[i]
                list_of_numbers[i] = list_of_numbers[i+1]
                list_of_numbers[i+1] = temp
    
    return list_of_numbers

print(bubble_sort())



[1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 8]


In [ ]:

frame = pd.DataFrame({
    "a": np.random.standard_normal(100),
    "b": np.random.standard_normal(100)
})

store = pd.HDFStore("przykłady/mydata.h5")

store.put("obj1", frame, format='table')

store["obj1_col_a"] = frame["a"]
store["obj1_col_b"] = frame["b"]

filtred = store.select('obj1', where=['index >= 10 and index <= 15'])

store.put('obj2', filtred, format='table')

store.close()

store = pd.HDFStore("przykłady/mydata.h5")
print(store['obj2'])
store.close()
os.remove("przykłady/mydata.h5")


           a         b
10  0.016824  0.619190
11 -0.372029  0.326705
12 -0.349033 -0.622438
13  1.692362  1.831231
14 -1.037186 -1.065389
15 -1.430797  0.716419


In [97]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

resp = requests.get(url)

resp.raise_for_status()

data = resp.json()
df = pd.DataFrame(data, columns=["number", "title"])
df

number                                              title
0    61055  BUG:  invalid result of reindex on columns aft...
1    61054                   BUG: Fix return type of loc/iloc
2    61052  BUG: sometimes when using ~ and & operators fo...
3    61050                Adjust Docker File Key Value Format
4    61049  BUG: Ghost Column Generation Bug in .loc[] wit...
5    61046  perf: improve membership check performance in ...
6    61045  PERF: Optimize membership check in column filt...
7    61041                 BUG: Recognize chained fsspec URLs
8    61037   Metadata generation failed when installing PyQt5
9    61036     Correction: Adjust Dockerfile key value format
10   61035  BUG: fix DataFrame.__setitem__ throwing a Valu...
11   61033            ENH: Add `coalesce_keys` option to join
12   61032   [WIP] Allow JIT compilation with an internal API
13   61031  BUG: `ValueError: ndarray is not C-contiguous`...
14   61030  BUG: Dependency check custom error loses infor...
15   61029  BUG: Printing float16 with NumPy>=2.0 gives ov...
16   61026    BUG: setting column with 2D object array raises
17   61025  BUG: Arugment nan_as_null is unused in __dataf...
18   61024                                  Fixed describe.py
19   61020  DOC: df.plot() is missing color parameter on d...
20   61019  BUG: df.plot() multi-column subplots & title i...
21   61018  BUG: df.plot() "Subplots" changes behavior of ...
22   61006          ENH: json_normalize should work with JSON
23   61005  BUG: scatter and line matplotlib plots not com...
24   60999         ENH: Pass col_len to on_bad_lines callable
25   60998  ENH: Add `to_numeric_br()` function to convert...
26   60997  BUG: fix read_json ignoring the dtype with the...
27   60994  BUG: `iloc` with `Series` as indexer fails for...
28   60993  ENH(string dtype): fallback for HDF5 with UTF-...
29   60992  BUG: fix PeriodIndex.difference producing inco...

In [ ]:
querry = """
        CREATE TABLE test
        (a VARCHAR(20), b VARCHAR(20),
        c REAL, d INTEGER);"""

con = sqlite3.connect('mydata.sqlite')
con.execute(querry)
con.commit()

data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Polska', 'Warszawa', 3.34, 3),
        ('Rzym', 'Watykan', 2.43, 8)]

stmt = 'INSERT INTO test VALUES(?,?,?,?)'
con.executemany(stmt, data)
con.commit()



[('Georgia',), ('Warszawa',), ('Watykan',)]

In [ ]:
cursor = con.execute('SELECT * from test')
rows = cursor.fetchall()

cursor.description

df = pd.DataFrame(rows, columns=[x[0] for x in cursor.description])


a         b     c  d
0  Atlanta   Georgia  1.25  6
1   Polska  Warszawa  3.34  3
2     Rzym   Watykan  2.43  8

In [138]:
import sqlalchemy as sqla

db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql("SELECT * FROM test", db)



a         b     c  d
0  Atlanta   Georgia  1.25  6
1   Polska  Warszawa  3.34  3
2     Rzym   Watykan  2.43  8